spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none 
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false